version: '3.8'
services:
  backend:
    build:
      context: ./cadastro-usuarios
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./cadastro-usuarios:/app
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development