name: Push-to-EC2
on:
  push:
    branches: [main, staging]
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      
      - name: Copy files with SSH
        uses: julianacamil/dev@main

        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          SOURCE: "./"
          REMOTE_HOST: "ec2-54-90-78-36.compute-1.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user"
